apiVersion: v1
kind: Pod
metadata: 
  labels:
    app: job
  name: benchmark-tools-pod
spec: 
  containers: 
    - 
      args:
        - daemon
      image: "skcho4docker/jre8-benchmark-tools:ver1.0.0"
      name: benchmark-tools
      resources: 
        limits: 
          cpu: 4 
          memory: 16Gi  
        requests: 
          cpu: 4 
          memory: 16Gi
