apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1.0.2
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.0.2
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.0.2
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.0.2
    spec:
      serviceAccount: heapster
      containers:
        - image: gcr.io/google_containers/heapster:v1.0.2
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 208Mi
            requests:
              cpu: 100m
              memory: 208Mi
          command:
            - /heapster
            - --source=kubernetes.summary_api:http://10.196.187.254:80?inClusterConfig=false&useServiceAccount=true&auth=
            #- --source=kubernetes:http://10.196.187.254:80?inClusterConfig=false&useServiceAccount=true&auth=
            #- --source=kubernetes.summary_api:http://10.196.187.254:80
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --metric_resolution=60s
        - image: gcr.io/google_containers/heapster:v1.0.2
          name: eventer
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 205800Ki
            requests:
              cpu: 100m
              memory: 205800Ki
          command:
            - /eventer
            #- --source=kubernetes:http://10.196.187.254:80?inClusterConfig=false&useServiceAccount=true
            - --source=kubernetes:http://10.196.187.254:80?inClusterConfig=false&useServiceAccount=true&auth=
            #- --source=kubernetes:''
            #- --source=kubernetes:http://10.196.187.254:80
            - --sink=influxdb:http://monitoring-influxdb:8086
        - image: gcr.io/google_containers/addon-resizer:1.0
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0m
            - --memory=208Mi
            - --extra-memory=4Mi
            - --threshold=5
            - --deployment=heapster-v1.0.2
            - --container=heapster
            - --poll-period=300000
        - image: gcr.io/google_containers/addon-resizer:1.0
          name: eventer-nanny
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0m
            - --memory=205800Ki
            - --extra-memory=500Ki
            - --threshold=5
            - --deployment=heapster-v1.0.2
            - --container=eventer
            - --poll-period=300000
