apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    type: cache 
  type: ClusterIP
  #type: NodePort
  #type: LoadBalancer 
  #type: LoadBalancer 
  clusterIP: 192.168.3.12
