apiVersion: v1
kind: ReplicationController
metadata: 
  name: redis-controller
  namespace: default
  labels:
    type: cache 
    kubernetes.io/cluster-service: "true"
spec: 
  replicas: 1
  selector: 
    type: cache
  template: 
    metadata: 
      labels: 
        type: cache
        kubernetes.io/cluster-service: "true"
      name: redis-pod
    spec: 
      containers: 
        - 
          args: 
            - daemon
          image: "skcho4docker/redis-2.8.17:ver1.0.0"
          name: redis
          ports: 
            - 
              containerPort: 6379
              protocol: TCP
