apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    stack: gate
  name: spin-gate-nodeport
  namespace: spinnaker
spec:
  type: NodePort
  ports:
  - name: http
    port: 8084
    protocol: TCP
    nodePort: 30599
    #targetPort: 8084
  - name: monitoring
    port: 8008
    protocol: TCP
    nodePort: 30749
    #targetPort: 8008
  selector:
    load-balancer-spin-gate: "true"
  sessionAffinity: None
