apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    stack: deck
  name: spin-deck-nodeport
  namespace: spinnaker
spec:
  type: NodePort
  ports:
  - name: http
    port: 9000
    protocol: TCP
    nodePort: 31442
    #targetPort: 9000
  - name: monitoring
    port: 8008
    protocol: TCP
    nodePort: 31131
    #targetPort: 8008 
  selector:
    load-balancer-spin-deck: "true"
  sessionAffinity: None
