apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    stack: clouddriver
  name: spin-clouddriver-nodeport
  namespace: spinnaker
spec:
  type: NodePort
  ports:
  - name: http
    port: 7002
    protocol: TCP
    nodePort: 31443
    #targetPort: 7002
  - name: monitoring
    port: 8008
    protocol: TCP
    nodePort: 31132
    #targetPort: 8008
  selector:
    load-balancer-spin-clouddriver: "true"
  sessionAffinity: None
