apiVersion: v1
kind: Service
metadata:
  name: default-http-backend-injected
  namespace: kube-system
  labels:
    k8s-app: default-http-backend-injected
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: default-http-backend-injected
  type: ClusterIP
  #type: NodePort
  #type: LoadBalancer 
