apiVersion: v1
kind: Service
metadata:
  name: zipkin-nodeport
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 9411
  selector:
    app: zipkin
  #type: ClusterIP
  type: NodePort
  #type: LoadBalancer
  #clusterIP: 192.168.3.14
---
