apiVersion: v1
kind: Service
metadata:
  name: mallconfig-service
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
  selector:
    api: mallconfig-api
  #type: ClusterIP
  type: NodePort
  #type: LoadBalancer 
  #type: LoadBalancer 
  clusterIP: 192.168.3.13
