apiVersion: v1
kind: Service
metadata:
  name: merchant-service
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    #nodePort: 30001
    protocol: TCP
  selector:
    api: merchant-api
  #type: ClusterIP
  #type: NodePort
  #type: LoadBalancer 
  type: LoadBalancer 
  #clusterIP: 192.168.3.14
