apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: rabbitmq
  namespace: arp-micro 
  labels:
    type: mq 
    kubernetes.io/cluster-service: "true"
spec: 
  replicas: 1
  #selector: 
    #type: db
  template: 
    metadata: 
      labels: 
        type: mq 
        mq: rabbitmq
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: "bitnami/rabbitmq:3.7.4-r3"
          name: rabbitmq 
          ports: 
            - 
              containerPort: 4369 
              protocol: TCP
            -
              containerPort: 5672 
              protocol: TCP
            -
              containerPort: 25672 
              protocol: TCP
            -
              containerPort: 15672 
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /bitnami
              name: rabbitmq-volume
      volumes:
        - 
          hostPath:
            path: /usr/local/var/rabbitmq
          name: rabbitmq-volume

