apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  ports:
  - port: 9090
    targetPort: 9090
    #nodePort: 30001
    protocol: TCP
  selector:
    app: prometheus
  #type: ClusterIP
  type: NodePort
  #type: LoadBalancer 
  #type: LoadBalancer 
  #clusterIP: 192.168.3.14
